// @ts-nocheck
'use client'
import { useState } from 'react'
import { AlertTriangle, ListChecks, Radio } from 'lucide-react'
import type { Risk, RiskMetric } from '@/types/risk'
const badge: Record<string, string> = { low: 'border-emerald-200 bg-emerald-50 text-emerald-700', medium: 'border-amber-200 bg-amber-50 text-amber-700', high: 'border-red-200 bg-red-50 text-red-700', critical: 'border-red-200 bg-red-50 text-red-700' }
const text = (v: unknown) => typeof v === 'string' || typeof v === 'number' ? String(v) : ''
function Metrics({ metrics }: { metrics: RiskMetric[] }) { return metrics.length ? <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((m, i) => <div key={`${m.key}-${i}`} className="rounded-lg border border-slate-200 bg-slate-50/70 px-3 py-2.5"><p className="truncate text-[10px] font-semibold uppercase tracking-[0.06em] text-slate-500">{m.label || 'Metric'}</p><p className={`mt-1 break-words text-[17px] font-bold ${m.highlight ? 'text-red-600' : 'text-slate-900'}`}>{m.value || text(m.raw_value) || '—'}</p></div>)}</div> : null }
export function Preview({ risk }: { risk: Risk }) {
  const [detailsOpen, setDetailsOpen] = useState(false), [mitigationOpen, setMitigationOpen] = useState(false)
  const details = risk.details, items = details.items || [], exposure = details.underlying_exposure || [], impact = details.impact || [], steps = Array.isArray(risk.mitigation) ? risk.mitigation : risk.mitigation?.steps || []
  return <div className="min-w-0 rounded-lg bg-slate-50/80 p-3 sm:p-4 lg:p-5"><article className="overflow-hidden rounded-[10px] border border-slate-200 bg-white shadow-sm"><div className="p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-2.5"><AlertTriangle className="mt-1 size-[18px] shrink-0 text-red-500" /><div><h2 className="break-words text-[19px] font-bold leading-6 text-slate-950 sm:text-[21px]">{risk.title || 'Risk notification'}</h2>{risk.subtitle && <p className="mt-1 text-[13px] text-slate-500">{risk.subtitle}</p>}</div></div><span className={`shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${badge[risk.severity] || badge.high}`}>{risk.severity_label || risk.severity}</span></div>{risk.summary && <p className="mt-5 text-[13px] leading-5 text-slate-700"><b className="text-slate-900">Summary.</b> {risk.summary}</p>}<div className="mt-5"><Metrics metrics={risk.metrics || []} /></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => { setDetailsOpen(v => !v); setMitigationOpen(false) }} className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-[12px] font-semibold text-slate-700"><AlertTriangle className="size-3.5 text-red-500" />View Details</button><button type="button" onClick={() => { setMitigationOpen(v => !v); setDetailsOpen(false) }} className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-[12px] font-semibold text-slate-700"><ListChecks className="size-3.5" />Mitigation Plan</button></div></div><div className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-200 px-4 py-3 text-[11px] text-slate-500"><span className="font-semibold">{risk.sender?.name || 'StratSync Risk Monitor'} · Risk ID {risk.risk_id || '—'}</span><span>Detected {risk.detected_time || '—'}</span></div></article>
  {detailsOpen && <article className="mt-3 rounded-[10px] border border-slate-200 bg-white p-4 shadow-sm"><p className="mb-3 text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">Reply • Risk Details</p><h3 className="mb-3 text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">{details.section_title || 'Risk Details'}</h3>{items.length > 0 && <ul className="space-y-2 text-[13px] text-slate-700">{items.map((item, i) => <li key={i}><b>{item.label}</b>{item.label && item.value ? ': ' : ''}{item.value}</li>)}</ul>}{exposure.length > 0 && <ul className="mt-4 list-disc pl-5 text-[13px] text-slate-700">{exposure.map((item, i) => <li key={i}>{item}</li>)}</ul>}{impact.length > 0 && <><h3 className="mb-3 mt-5 text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">Impact</h3><ul className="list-disc pl-5 text-[13px] text-slate-700">{impact.map((item, i) => <li key={i}>{item}</li>)}</ul></>}</article>}
  {mitigationOpen && <article className="mt-3 rounded-[10px] border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">Reply • Mitigation Plan</p><h2 className="mt-2 text-[18px] font-bold text-slate-950">Mitigation Plan</h2>{risk.mitigation?.summary && <p className="mt-1 text-[13px] text-slate-500">{risk.mitigation.summary}</p>}<div className="mt-4 divide-y divide-slate-100">{steps.map((step, i) => <div key={i} className="py-3"><p className="text-[13px] font-bold">{step.title || `Step ${i + 1}`}</p>{step.description && <p className="text-[12px] text-slate-600">{step.description}</p>}{step.owner && <p className="mt-1 text-[11px] text-slate-400">Owner: {step.owner}</p>}</div>)}</div><div className="mt-3 flex items-center justify-between border-t border-slate-200 pt-3 text-[11px] text-slate-400"><span>Last updated: {risk.mitigation?.last_updated || risk.updated_at || '—'}</span><Radio className="size-3.5" /></div></article>}</div>
}
